### ISSUE TITLE
R4Mvc Does not work in multitarget projects

### ISSUE THREAD

**Issue by jack128** [T4MVC/R4MVC#106] opened 2018-09-06 12:33 UTC
"does not work" mean "does not generate XXXController.generated.cs  files".

Example of project:

```xml
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp2.1;net462</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp2.1' ">
    <PackageReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="Microsoft.AspNetCore" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.CookiePolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.HttpsPolicy" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.6" />

    <Reference Include="System.Configuration" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="R4Mvc" Version="1.0.0-alpha1-00269" />
    <PackageReference Include="R4Mvc.Tools" Version="1.0.0-alpha1-00269">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

**Comment by artiomchi** [comment] 2018-09-06 13:41
This is actually already known, but wasn't the highest priority, since nobody actually used multi-targeting (or reported to so far) :)

I'll close this issue, since this is a duplicate of #66 
You can track the progress there. I'll try to prioritise this, and hopefully get something working before the next release!

**Closed as completed by artiomchi** 2018-09-06 13:41 UTC
Labels: bug

**Comment by artiomchi** [comment] 2018-09-12 09:38
Hey @jack128, we've got a decent solution to this, mentioned in the main issue. I'll be releasing it to NuGet soon, but you can already pick it up from MyGet :)

Would love to hear back to see if it works for you as well
