### ISSUE TITLE
R4MVC fails on msbuild warnings

### ISSUE THREAD

**Issue by valeriob** [T4MVC/R4MVC#119] opened 2019-04-16 07:37 UTC
Hi,
i'm porting an aspnet mvc project to aspnetcore, and it's using some library on witch i have no control on, it fails on msbild warning :

> Msbuild failed when processing the file 'pathto.csproj' with message: pathto.csproj: (0, 0): Package 'MyPackage 4.0.30.113024' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.2'. This package may not be fully compatible with your project.

I know about the warning, the compilation step tell me that, but i want to ignore it on generating r4mvc, it should really not interfeere.
Do you know any switch on msbuild to suppress this ? I guess like the compilation does, because i can make an aspnetcore 2.2 app referencing that package successfully.

Thanks

**Comment by valeriob** [comment] 2019-04-23 09:22
@artiomchi do you have any idea ? 😄 
I tried to ask the same question to the msbuild repo : https://github.com/Microsoft/msbuild/issues/4314

**Comment by artiomchi** [comment] 2019-04-23 18:30
Hey @valeriob, sorry I'm a bit away, so didn't get to check this out. By the way, this is a duplicate of #115, so I'll close this and update the issue there with a solution

**Comment by artiomchi** [comment] 2019-04-23 18:30
Duplicate of #115

**Closed as completed by artiomchi** 2019-04-23 18:30 UTC
