### ISSUE TITLE
MsBuild Failure FindDependenciesOfExternallyResolvedReferences parameter not supported

### ISSUE THREAD

**Issue by valeriob** [T4MVC/R4MVC#89] opened 2018-01-24 09:59 UTC
Running Generate-r4mvc in a machine with just VS 2017 15.6.0 preview 2  produces the following error:

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:   Failure: Msbuild failed when processing the file 'C:\blalbla\ProjectWeb.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (2089, 9): The "FindDependenciesOfExternallyResolvedReferences" parameter is not supported by the "ResolveAssemblyReference" task. Verify the parameter exists on the task, and it is a settable public instance property.

I'm not able to reproduce it if in the same machine vs 15.5.x is installed, maybe due to something in Path  contaminating the environment ?

**Comment by valeriob** [comment] 2018-01-24 10:28
I uninstalled VS 2017 15.5 (so only the preview remains installed) and started failing, so there is definitely some interference between the two :(
I tried in another machine, now it fails even with vs 2017 15.5 installed.

**Comment by artiomchi** [comment] 2018-01-24 22:48
Oh man, not again! I thought we were done with this with the 15.5 beta release!

Initially it was an issue with the MSBuild assembly. I wonder what's up with it this time.

Don't want to compromise my main machine, so I'll set up a temp VM where I will try to replicate it and see what's up.

I see your #90 PR, but I don't want to merge it straight away before I check what's up with the issue first and what's causing it.

**Comment by valeriob** [comment] 2018-01-25 05:58
Ofc ! 😀

**Comment by valeriob** [comment] 2018-02-06 07:49
Hi @artiomchi did you reproduce it ? i could really use that update 😄

**Comment by artiomchi** [comment] 2018-02-07 12:34
Sorry, I can't believe I got stuck for two weeks!

Umm, I just set up an environment with VS 2017 15.5.6 + 15.6 preview 3, but I can't reproduce the issue.

I wonder if it's something relating to your project specifically, or an issue with preview 2 that they fixed?

Very sorry that it took so long. At least I fixed my github notifications, so now I'm actually getting my emails!

If it still doesn't work for you with the latest preview, could you try make a simple test project that I can reproduce it with?

**Comment by valeriob** [comment] 2018-02-07 13:01
Hi @artiomchi no problem at all 😄 
I just did file new project, added r4mvc tools 1.0.0-alpha1-00211 and it fails with
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:   Failure: Msbuild failed when processing the file 'C:\Users\vborioni\Source\Repos\WebApplication3\WebApplication3\WebApplication3.csproj' with message: C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets: (2089, 9): The "FindDependenciesOfExternallyResolvedReferences" parameter is not supported by the "ResolveAssemblyReference" task. Verify the parameter exists on the task, and it is a settable public instance property.

If i run the PR with updated msbuild it works, as i told you i had problems reproducing it myself, now i can't make it work on a computer with both preview and standard.

**Comment by artiomchi** [comment] 2018-02-07 18:26
Well that's weird. I just created a new project in the VS Preview, and it worked perfectly fine. Seems like VS preview builds are causing some corruption with the build runtime again.

Unfortunately, I still can't reproduce it, as it seems like this is a problem with your local environment.

Let's see if it's related to the issue they had last time or not. Try setting the `VSINSTALLDIR` environment variable to your VS path (something like `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`?). Also set `VisualStudioVersion` to `15.0`. Restart and see if it works.

Also, try run the latest CI build, and pass here the full output? Let's see which versions of MSBuild are being loaded into the project

**Comment by artiomchi** [comment] 2018-02-09 06:59
Hey @valeriob 

I can see that the final preview build of VS just came out yesterday. Could you take a look if that release fixes the issue as well?

**Comment by valeriob** [comment] 2018-02-09 08:59
Hi @artiomchi i tried latest version, this is the output from any vs (both 2017 and preview): 

Project path: E:\GitHub\R4MVC\src\R4Mvc.Tools\..\R4MvcHostApp\R4MvcHostApp.csproj
MSBuild loaded assemblies (stage: clean workspace):
  Microsoft.CodeAnalysis.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.dll
  Microsoft.CodeAnalysis: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.dll
  Microsoft.CodeAnalysis.Workspaces.Desktop: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.Desktop.dll
  Microsoft.CodeAnalysis.CSharp: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.dll
  Microsoft.CodeAnalysis.CSharp.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.Workspaces.dll
  Microsoft.Build: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.dll
  Microsoft.Build.Framework: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Framework.dll
  Microsoft.Build.Tasks.Core: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Tasks.Core.dll
MSBuild loaded assemblies (stage: project loaded):
  Microsoft.CodeAnalysis.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.dll
  Microsoft.CodeAnalysis: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.dll
  Microsoft.CodeAnalysis.Workspaces.Desktop: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.Desktop.dll
  Microsoft.CodeAnalysis.CSharp: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.dll
  Microsoft.CodeAnalysis.CSharp.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.Workspaces.dll
  Microsoft.Build: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.dll
  Microsoft.Build.Framework: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Framework.dll
  Microsoft.Build.Tasks.Core: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Tasks.Core.dll
  Failure: Msbuild failed when processing the file 'E:\GitHub\R4MVC\src\R4MvcHostApp\R4MvcHostApp.csproj' with message: MSB0001: Internal MSBuild Error: Missing resource ''

If i run it from Developer command prompt preview i get the same result, it works if i run from the NON-Preview Developer Command prompt : 

e:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462>dotnet-r4mvc E:\GitHub\R4MVC\src\R4MvcHostApp\R4MvcHostApp.csproj
Project path: E:\GitHub\R4MVC\src\R4MvcHostApp\R4MvcHostApp.csproj
MSBuild loaded assemblies (stage: clean workspace):
  Microsoft.CodeAnalysis.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.dll
  Microsoft.CodeAnalysis: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.dll
  Microsoft.CodeAnalysis.Workspaces.Desktop: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.Desktop.dll
  Microsoft.CodeAnalysis.CSharp: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.dll
  Microsoft.CodeAnalysis.CSharp.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.Workspaces.dll
  Microsoft.Build: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.dll
  Microsoft.Build.Framework: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Framework.dll
  Microsoft.Build.Tasks.Core: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Tasks.Core.dll
MSBuild loaded assemblies (stage: project loaded):
  Microsoft.CodeAnalysis.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.dll
  Microsoft.CodeAnalysis: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.dll
  Microsoft.CodeAnalysis.Workspaces.Desktop: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.Workspaces.Desktop.dll
  Microsoft.CodeAnalysis.CSharp: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.dll
  Microsoft.CodeAnalysis.CSharp.Workspaces: 2.6.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.CodeAnalysis.CSharp.Workspaces.dll
  Microsoft.Build: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.dll
  Microsoft.Build.Framework: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Framework.dll
  Microsoft.Build.Tasks.Core: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Tasks.Core.dll
  Microsoft.Build.Utilities.Core: 15.1.0.0 from E:\GitHub\R4MVC\src\R4Mvc.Tools\bin\Debug\net462\Microsoft.Build.Utilities.Core.dll
  Microsoft.Build.Utilities.v4.0: 4.0.0.0 from C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Build.Utilities.v4.0\v4.0_4.0.0.0__b03f5f7f11d50a3a\Microsoft.Build.Utilities.v4.0.dll
  Microsoft.Build.Tasks.CodeAnalysis: 2.6.0.0 from C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Roslyn\Microsoft.Build.Tasks.CodeAnalysis.dll

**Comment by artiomchi** [comment] 2018-03-06 15:55
Heya,

So VS 15.6 was finally released and I just tested R4Mvc with it, and it is still working perfectly fine. Either it was an issue limited to your environment or something with the RC build of VS (which I couldn't replicate either).

Also it's possible that the commit above has fixed the issue too.

In either case, the issue seems to no longer be there, so I'm closing this.

If it's still happening in your environment, and you can replicate it (and help us replicate it), we can reopen the issue again

**Closed as completed by artiomchi** 2018-03-06 15:55 UTC
Labels: bug
